POST http://localhost:8080/profiles
Content-Type: application/json

{
    "description": "Teste"
}

###
GET http://localhost:8080/profiles

###
GET http://localhost:8080/profiles/1

###
PUT http://localhost:8080/profiles/5
Content-Type: application/json

{
    "description": "Teste 5"
}

###
DELETE http://localhost:8080/profiles/2

###
GET http://localhost:8080/users

###
GET http://localhost:8080/users/1

###
POST http://localhost:8080/users
Content-Type: application/json

{
    "name": "Guilherme",
    "profileIDs": [1,2,3]
}

###
PUT http://localhost:8080/users/1
Content-Type: application/json

{
    "name": "Guilherme 1",
    "profileIDs": [1,2]
}

###
DELETE http://localhost:8080/users/1